baseURL = "https://blog.gzhh.tech"
title = "gzhh's blog"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false # use git commit log to generate lastmod record # 可根据 Git 中的提交生成最近更新记录。

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "gzhh-tech"

[params]
  author = "gzhh"
  info = "Stay Hungry Stay Foolish"
  description = "gzhh's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "zhonghuangao@gmail.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2017

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/gzhh/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/gaozhonghuan/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3 
  url = "https://www.instagram.com/gaozhonghuan/"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss-square fa-2x"
  weight = 4
  url = "/index.xml"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
# [[menu.main]]
#   name = "Work"
#   weight = 2
#   url  = "work/"
# [[menu.main]]
#   name = "Life"
#   weight = 2
#   url  = "life/"
[[menu.main]]
  name = "Read"
  weight = 3 
  url  = "read/"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about/"
# [[menu.main]]
#  name = "Logseq"
#  weight = 4 
#  url = "https://logseq.gzhh.tech/"
# [[menu.main]]
#  name = "Notion"
#  weight = 5 
#  url = "https://notion.gzhh.tech/"

[markup.goldmark.extensions]
  linkfy = false # 禁止 https 页面跳转到 http 页面
[markup.goldmark.renderer]
  unsafe = true # table 单元格开启 <br> 换行，参考 https://gohugo.io/getting-started/configuration-markup#config


